public class date {
    private static String v = "verb";
    private static String n = "noun";
    private static String ad = "adjective";
    /*
    /2015卷 不知道单词库
     */
    public static word[] WordDate_2015 = {
            new word("withdrawn","回收、收回",""),
            new word("separate","分开","verb"),
            new word("insignificant","微不足道的","adjective"),
            new word("unreliable","不可靠的","adjective"),
            new word("incredible","极好的","adjective"),
            new word("resemble","相似","verb"),
            new word("favor","喜爱","verb"),
            new word("surpass","超越","verb"),
            new word("regardless of","不管不顾","词组"),
            new word("along with","与什么一道","词组"),
            new word("forecast","预报","verb"),
            new word("unpredictable","不可预测的能力","adjective"),
            new word("contributory","促成的","adjective"),
            new word("disruptive","摧毁的","adjective"),
            new word("endeavor","尝试","verb"),
            new word("religious","宗教的","adjective"),
            new word("ethnic","民族的","adjective"),
            new word("analysis on","在...上分析","词组-注意on"),
            new word("there is more to it","对于这个远远不止这些这么简单","注意词组的 to"),
            new word("pick pace","加速","词组"),
            new word("abdicate","退位","verb"),
            new word("embarrassing","尴尬的","adjective"),
            new word("scandal","丑闻","noun"),
            new word("eat one's words","失言-不讲信用","词组"),
            new word("stand down","退位","词组"),
            new word("the writing is on the wall","一般形容不好的事情被好多人知道了（被人肉了）涂墙了","词组"),
            new word("argument","论据","noun"),
            new word("polarised","两极化","noun"),
            new word("mere","纯粹","noun"),
            new word("embody","象征","noun"),
            new word("transcendence","超越,神！一般的存在","noun"),
            new word("excepted","除此之外","verb"),
            new word("monarchy","君主","noun"),
            new word("royals","贵族-皇室（一般形容西欧）","noun"),
            new word("regime","政权","noun"),
            new word("infested","泛滥(monarch-infested)","verb"),
            new word("absolutist","绝对主义（专制主义者）","noun"),
            new word("counterpart","..。职务相当的人（需要增补，目前形容不到位）","noun"),
            new word("non-controversial","无争议的","adjective"),
            new word("indefensible","不可捍卫的（无力的那种噢）","adjective"),
            new word("inequalities","自己拼（in-反，equal-平等）不平等的","adjective"),
            new word("inherit","继承","verb"),
            new word("bizarre","离奇","adjective"),
            new word("aristocratic","皇室的，贵族的","adjective"),
            new word("strive to","努力去","注意 to"),
            new word("Princes","英俊的‘王子’","noun"),
            new word("Princesses","白雪的'公主'","noun"),
            new word("the international 1%","全球前百分之一的有钱人","词组，有点难直接看出意思的那种（恶心心）"),
            new word("intrusiveness","干扰","noun"),
            new word("preserved","保持","verb"),
            new word("granny style","老奶奶风","noun-词组"),
            new word("hierarchical","封建分级的那种","adjective"),
            new word("eased","放缓","verb"),
            new word("rival","对手","noun"),
            new word("democracies","民主","noun"),
            new word("Constitution","宪法","Noun"),
            new word("arrest","逮捕","noun/verb"),
            new word("refrain form","远离什么","我没有什么好说的了"),
            new word("sweeping","全面的","adjective"),
            new word("assumption","假设.寓言","noun"),
            new word("authorities","执法者","noun"),
            new word("possessions","财产","noun"),
            new word("argues","发言-认为","verb"),
            new word("discard","抛弃-放弃","verb"),
            new word("lame","低级的-粗俗的","adjective"),
            new word("purse","钱包","noun"),
            new word("violate","违抗","verb"),
            new word("medical","医疗的","adjective"),
            new word("devices","设备","noun"),
            new word("burdensome","复杂的-繁琐的","adjective"),
            new word("invalidate","证明...是错误的，使无效","verb"),
            new word("urgent","紧急","adjective"),
            new word("circumstances","情况","noun"),
            new word("erased","擦掉","verb"),
            new word("swallow","吞（A swallow B'words 可以表示A听B的话)","verb"),
            new word("novel","新颖的","adjective"),
            new word("application","应用","noun"),
            new word("establishment","成立","noun"),
            new word("automobile","摩托车","noun"),
            new word("virtual","虚拟的","adjective"),
            new word("necessity","必要性","noun"),
            new word("domain","某一领域","noun"),
            new word("passenger","乘客","noun"),
            new word("sort out","解决（deal with)","词组"),
            new word("prevent","阻碍和preserve 保留 区分一下","verb"),
            new word("prohibit","禁止","verb"),
            new word("indifference","不关心","noun"),
            new word("cautiousness","谨慎","noun"),
            new word("residence","住所","noun"),
            new word("implemented","实行","verb"),
            new word("flexible","灵活的","adjective"),
            new word("journal","日报-报刊","noun"),
            new word("statistical","统计学","noun"),
            new word("effect","举措","noun"),
            new word("irreproducibility","不可复制性","noun"),
            new word("Manuscript","手稿","noun"),
            new word("scrutiny","详细调查","noun"),
            new word("panel","小组","noun"),
            new word("impelled","推进","verb"),
            new word("board","委员会 同council","noun"),
            new word("advisory","可以提供意见的","adjective"),
            new word("impact","影响","noun"),
            new word("publications","作用力","noun"),
            new word("long overdue","这东西早该来了的","嘿嘿嘿"),
            new word("essential","必要","noun-adjective"),
            new word("literate","文学的","noun-adjective"),
            new word("tougher","严格的","adjective"),
            new word("verify","确认","verb"),
            new word("merit","积极的","adjective"),
            new word("simplify","简化的","adjective"),
            new word("threat","危险","noun"),
            new word("circulation","发行量-点击率（一般和新闻界有关）","noun"),
            new word("diminishes","降低","verb"),
            new word("unset","沮丧","verb"),
            new word("integrity","正义","noun"),
            new word("institution","情况","noun"),
            new word("collapsed","崩塌","verb"),
            new word("collective","集中的,收集的","adjective"),
            new word("acceptance","认识","noun"),
            new word("mechanism","机制","noun"),
            new word("capitalism","资本主义","noun"),
            new word("wounding","伤口","noun"),
            new word("frame","表达","verb"),
            new word("astonishing","惊人的","adjective"),
            new word("revelations","被揭示的现象","noun"),
            new word("doctrine","教条","noun"),
            new word("margin","边界","noun"),
            new word("degraded","降至","verb"),
            new word("betray","暴露","verb"),
            new word("ruin","毁掉","verb"),
            new word("quest","寻找","verb"),
            new word("deny","否定","verb"),
            new word("certain","包括","adjective"),
            new word("reveal","揭露","verb"),
            new word("cunning","狡诈的","adjective"),
            new word("centered","集中于","verb"),
            new word("trivial","无关紧要的","adjective"),
            new word("convincing","说服","noun"),
            new word("conspiracy","共谋","noun"),
            new word("distorted","扭曲的","adjective"),
            new word("distribution","分配","noun"),
            new word("rigid","传统-死板的","adjective"),
            new word("aware","知道-了解","verb"),

    };

    public static word[] WordDate_2016 = {
            new word("involve","涉及.包含.","verb"),
            new word("matchmaker","匹配制造者（人话叫'媒婆'）","noun"),
            new word("negotiation","协商","noun"),
            new word("vote","反对.否决","verb"),
            new word("investigate","调查.弄明白","verb"),
            new word("spouse","另一半~亲爱的！（较正式用法）","noun"),
            new word("affair","事件..的事儿","noun"),
            new word("Formerly","以前","副词副词"),
            new word("Buddhist ","佛教的","noun-adjective"),
            new word("priest","牧师、神父","noun"),
            new word("Cambodia","柬埔寨","noun"),
            new word("postpone","使....延期","verb"),
            new word("sermon","布道-训诫-启示","noun-verb"),
            new word("recite","背诵-吟诵","verb"),
            new word("prayer","祈祷-祷告文","noun"),
            new word("ceremony","典礼-庆祝活动","noun"),
            new word("ritual","礼仪的","adjective"),
            new word("cotton","棉花-棉质的","noun - adjective"),
            new word("thread","线","noun"),
            new word("soak","侵泡","verb"),
            new word("bride","女朋友","noun"),
            new word("groom","v-洗刷 n-马夫、夫君","verb-noun"),
            new word("wrists","手腕","noun"),
            new word("candle","蜡烛","noun"),
            new word("folding","对半拆开-对折","verb"),
            new word("piling","堆放","verb"),
            new word("wrapping","包裹（是包和裹，不是“包裹”）","verb"),
            new word("tying","系","verb"),
            new word("circle","循环","noun"),
            new word("association","联系","noun"),
            new word("divorce","离婚的-离婚的人","adjective-noun"),
            new word("obtain","实现","verb"),
            new word("disapproval","不赞同","noun"),
            new word("property","性质.财产（你的身价性质）","noun"),
            new word("jointly acquired","共同获得的","adjective"),
            new word("divide","分开","verb"),
            new word("gender","性别","noun"),
            new word("prejudice","偏见","noun"),
            new word("innovator","创新者","noun"),
            new word("preliminary","初步的、基础的","adjective"),
            new word("ultra (ultra-thin)","极度的、过度的","adjective"),
            new word("parliament","会议","noun"),
            new word("incite","煽动","verb"),
            new word("promote","促进、提升、发扬","verb"),
            new word("measures","方法","noun"),
            new word("uplifting","积极的（向上生活）","adjective"),
            new word("impinging on","侵犯、毁灭性的消弱","动词词组"),
            new word("tape","磁带、胶卷","noun"),
            new word("social tape-measure","社会尺度（我TM在看政治把）","名词词组"),
            new word("determine","下决定、做判读","verb"),
            new word("individual","个人的","adjective"),
            new word("cultivation","培养","verb"),
            new word("enforce","执行","verb"),
            new word("arbiter (be arbiter of )","裁判，定规矩的人","noun"),
            new word("hint","暗示","verb"),
            new word("intangible","无形的","adjective"),
            new word("wasp","蜜蜂","noun"),
            new word("waist","腰","noun"),
            new word("physique","身材","noun"),
            new word("punishment","惩罚","noun"),
            new word("index","指标数值-玩家角色属性","noun"),
            new word("mass","一坨，一团，民众","noun"),
            new word("inherent","遗留、继承","verb"),
            new word("material","材料 物质的","noun - adjective"),
            new word("adornment","装饰","noun"),
            new word("Denmark","丹麦","noun"),
            new word("voluntary","自愿的","adjective"),
            new word("contrast","对比","noun - verb"),
            new word("sanction","制裁","noun"),
            new word("revised","被修订的",ad),
            new word("deny","拒绝",v),
            new word("designer","设计师",n),
            new word("agencies","经纪人-代理人",n),
            new word("name-and-shame","'公开点名批评'",n),
            new word("compliance","服从",n),
            new word("in general","总体上","副词"),
            new word("ethical","伦理的",ad),
            new word("elevate","提升、举高",v),
            new word("indicate","表明",v),
            new word("constructed","建立",n),
            new word("faith in","对..信任",v),
            new word("threshold","门槛",n),
            new word("dilemma","两难的处境",n),
            new word("Threat","威胁",n),
            new word("curious","好奇的、有趣奇怪的",ad),
            new word("polls","投票、民意检测",n),
            new word("alongside","与..一样",v),
            new word("royal","贵族的",ad),
            new word("launch","开启、运作",v),
            new word("rescue","拯救",v),
            new word("stylish houses","时尚的领域",n),
            new word("specifically","特有的",ad),
            new word("dweller","居民",n),
            new word("leisure","空闲",n),
            new word("concrete","水泥",n),
            new word("constant","持续的",ad),
            new word("endorse","赞同",v),
            new word("sentiment","情况",n),
            new word("Conservation","保守党",n),
            new word("reform","改革",v),
            new word("explicitly","明确地",ad),
            new word("rural","农村的",ad),
            new word("priority","优先权",n),
            new word("authorise","批准",v),
            new word("object","拒绝",v),
            new word("concept","观念、形式",n),
            new word("sustainable","可持续的",ad),
            new word("profitable","有利益的.有钱赚的",ad),
            new word("Labour","劳动党",n),
            new word("council","委员会",n),
            new word("The Liberal Democrats","自由民主党",n),
            new word("silent","寂静",ad),
            new word("Ukip","独立党",n),
            new word("sensible","明智地",ad),
            new word("infrastructure","基础设施",n),
            new word("agents","代理人",n),
            new word("identified","明确",v),
            new word("intrusion","毁坏、对什么不利",n),
            new word("province","省",n),
            new word("crisis","危机",n),
            new word("meadows","草地、草坪",n),
            new word("renovation","改革、创新",n),
            new word("biased","有偏见的",ad),
            new word("sticks to","紧跟",v),
            new word("ruin","破坏",v),
            new word("rip","撕裂",v),
            new word("enviable","值得羡慕的",ad),
            new word("coherence","协调",n),
            new word("corrupted","被破坏",v),
            new word("promote","促进、提升",v),
            new word("spectrum","光谱",n),
            new word("overshadowed","被更大的东西覆盖、黯然失色（本身没有变）",ad),
            new word("protect","保护",v),
            new word("reinforce","加强",v),
            new word("destroyed","破坏",v),
            new word("abandon","抛弃",v),
            new word("disregard","忽视",n),
            new word("reveals","揭示",v),
            new word("prejudice","偏见",ad),

    };

    public static word[] WordDate_2014 = {
            new word("mental","大脑、精力的-精神病患者",n+ad),
            new word("band","乐队",n),

    };

    //总单词库
    public static Paper[] totalWordDate = {
            new Paper(WordDate_2015,"2015"),
            new Paper(WordDate_2016,"2016"),
            new Paper(WordDate_2014,"2017"),
    };
}
